from app.agents.orchestrator import graph
from langchain_core.messages import HumanMessage

def test_routing(user_query: str):
    print(f"\n--- Testing Query: '{user_query}' ---")
    initial_state = {"messages": [HumanMessage(content=user_query)]}
    
    for output in graph.stream(initial_state, {"recursion_limit": 10}):
        for node_name, state in output.items():
            print(f"Node triggered: {node_name}")
            if "messages" in state:
                # Print the last message generated by the node
                print(f"Message: {state['messages'][-1].content}")

if __name__ == "__main__":
    # Ask the AI to read a specific file from GitHub!
    test_routing("Can you read 'README.md' from the GitHub repository 'octocat/Hello-World' and tell me what it says?")