
from app.tools.rag_tools import search_uploaded_documents

from langgraph.prebuilt import create_react_agent
from app.tools.github import get_github_file_contents
import operator
import os
from typing import Annotated, Sequence, TypedDict, Literal

from dotenv import load_dotenv
from pydantic import BaseModel, Field

from langchain_core.messages import (
    BaseMessage,
    HumanMessage,
    AIMessage,
    SystemMessage,
)

from langchain_google_genai import ChatGoogleGenerativeAI

from langgraph.graph import StateGraph, START, END




load_dotenv()



class AgentState(TypedDict):
    messages: Annotated[Sequence[BaseMessage], operator.add]
    next_agent: str



class Route(BaseModel):
    next_agent: Literal[
        "coding_agent",
        "research_agent",
        "rag_agent",
        "reviewer_agent",
    ] = Field(
        description="The next agent to route the user's request to."
    )



def supervisor_node(state: AgentState) -> dict:
    """
    Supervisor decides which specialized agent should handle
    the user's request.
    """


    api_key = os.getenv("GOOGLE_API_KEY") or os.getenv("GEMINI_API_KEY")

    if not api_key:
        raise ValueError(
            "Gemini API key not found. "
            "Set GOOGLE_API_KEY or GEMINI_API_KEY in your .env file."
        )

    llm = ChatGoogleGenerativeAI(
        model="gemini-3.6-flash",
        api_key=api_key,
    )


    router = llm.with_structured_output(Route)

    

    system_prompt = """
You are the DevPilot AI Orchestrator.

Your job is to route the user's request to the most appropriate
specialized agent.

Available agents:

1. coding_agent
   Use for:
   - GitHub repository analysis
   - Debugging
   - Programming errors
   - Code reviews
   - FastAPI / React / Node.js issues
   - Software engineering problems

2. rag_agent
   Use for:
   - Questions about uploaded documents
   - PDFs
   - Personal knowledge bases
   - Document-based question answering

3. research_agent
   Use for:
   - General technical research
   - Technology comparisons
   - Framework comparisons
   - Documentation-style research
   - Current technical information

4. reviewer_agent
   Use only when the work of another agent has already been
   completed and a final synthesized response is required.

Return exactly one valid agent name.
"""

    # Prepare Messages
   

    messages = [
        SystemMessage(content=system_prompt),
        *list(state["messages"]),
    ]

  
    # Ask Gemini to Route
   

    decision = router.invoke(messages)

    print(f"[Supervisor] Selected agent: {decision.next_agent}")

    return {
        "next_agent": decision.next_agent
    }


# 4. Coding Agent

def coding_agent(state: AgentState) -> dict:
    print("[Coding Agent] Initializing ReAct Agent to analyze code...")

    api_key = os.getenv("GOOGLE_API_KEY") or os.getenv("GEMINI_API_KEY")

    if not api_key:
        raise ValueError(
            "Gemini API key not found. "
            "Set GOOGLE_API_KEY or GEMINI_API_KEY in your .env file."
        )

    # Use the SAME working Gemini model
    llm = ChatGoogleGenerativeAI(
        model="gemini-3.6-flash",
        api_key=api_key,
    )

    tools = [
        get_github_file_contents
    ]

    agent = create_react_agent(
        llm,
        tools,
    )

    system_prompt = SystemMessage(
        content=(
            "You are an elite AI Software Engineer. "
            "Use the get_github_file_contents tool to read code "
            "from the user's GitHub repository. "
            "Once you read the code, analyze it carefully. "
            "Find bugs, explain the root cause, and suggest fixes. "
            "Do not invent repository contents."
        )
    )

    input_messages = [
        system_prompt,
        *list(state["messages"]),
    ]

    result = agent.invoke(
        {
            "messages": input_messages
        }
    )

    # Only return messages generated by the ReAct agent
    new_messages = result["messages"][len(input_messages):]

    print("[Coding Agent] Analysis completed.")

    return {
        "messages": new_messages
    }
def research_agent(state: AgentState) -> dict:
    """
    Placeholder for the Research Agent.
    """

    print("[Research Agent] Processing request...")

    return {
        "messages": [
            AIMessage(
                content=(
                    "[Research Agent] "
                    "I would research the requested technology, "
                    "compare relevant solutions, and provide findings."
                )
            )
        ]
    }



# 6. RAG Agent


def rag_agent(state: AgentState) -> dict:
    print("[RAG Agent] Initializing ReAct Agent to search documents...")
    
    # 1. Setup LLM (Using the Pro model that worked for you earlier)
    api_key = os.getenv("GOOGLE_API_KEY") or os.getenv("GEMINI_API_KEY")
    llm = ChatGoogleGenerativeAI(
    model="gemini-3.6-flash",
    api_key=api_key,
)
    
    # 2. Give the agent our new Document Search tool
    tools = [search_uploaded_documents]
    agent = create_react_agent(llm, tools)
    
    # 3. Create the System Prompt
    system_prompt = SystemMessage(content=(
        "You are a helpful AI Document Assistant. "
        "Use the search_uploaded_documents tool to find answers in the user's PDFs. "
        "Always base your answers strictly on the context retrieved from the tool."
    ))
    
    input_messages = [system_prompt] + list(state["messages"])
    result = agent.invoke({"messages": input_messages})
    
    new_messages = result["messages"][len(input_messages):]
    return {"messages": new_messages}

# 7. Reviewer Agent


def reviewer_agent(state: AgentState) -> dict:
    """
    Placeholder for the final Reviewer Agent.
    """

    print("[Reviewer Agent] Creating final response...")

    summary = (
        "[Reviewer Agent] "
        "Here is the final synthesized response based on "
        "the specialist agent's work."
    )

    return {
        "messages": [
            AIMessage(content=summary)
        ]
    }



# 8. Build LangGraph


builder = StateGraph(AgentState)


# Add Nodes


builder.add_node("supervisor", supervisor_node)

builder.add_node(
    "coding_agent",
    coding_agent,
)

builder.add_node(
    "research_agent",
    research_agent,
)

builder.add_node(
    "rag_agent",
    rag_agent,
)

builder.add_node(
    "reviewer_agent",
    reviewer_agent,
)


# 9. Define Graph Edges


# START → Supervisor

builder.add_edge(
    START,
    "supervisor",
)

# Supervisor → Selected Agent


builder.add_conditional_edges(
    "supervisor",
    lambda state: state["next_agent"],
    {
        "coding_agent": "coding_agent",
        "research_agent": "research_agent",
        "rag_agent": "rag_agent",
        "reviewer_agent": "reviewer_agent",
    },
)



builder.add_edge(
    "coding_agent",
    "reviewer_agent",
)

builder.add_edge(
    "research_agent",
    "reviewer_agent",
)

builder.add_edge(
    "rag_agent",
    "reviewer_agent",
)



builder.add_edge(
    "reviewer_agent",
    END,
)



graph = builder.compile()


if __name__ == "__main__":
    print("DevPilot AI Agent Graph compiled successfully.")

